name: 'Delete Loft VCluster'
description: 'GitHub Action to delete a Loft VCluster'
author: loft.sh
inputs:
  name:
    required: true
    description: 'The name of the vcluster to delete'
  cluster:
    required: false
    description: 'The cluster on which to delete the vcluster (if there are multiple vclusters with the same name across multiple clusters)'
  project:
    required: false
    description: "The project to use"
  space:
    required: false
    description: 'The space on which to delete the vcluster (if there are multiple vclusters with the same name across multiple spaces)'
  delete-space:
    required: false
    description: Should the corresponding space be deleted
    default: true
runs:
  using: 'node12'
  main: 'dist/index.js'
